export const danishAlphabet = [
  // + norwegian
  // a	b	c	d	e	f	g	h	i	j	k	l	m	n	o	p	q	r	s	t	u	v	w	x	y	z	æ	ø	å
]; ``
// sv
// a	b	c	d	e	f	g	h	i	j	k	l	m	n	o	p	q	r	s	t	u	v	w	x	y	z	å ä ö

export const KEYS = [
  // Letter keys.
  { key: 'a', color: 'orange' },
  { key: 'b', color: 'red' },
  { key: 'c', color: 'green' },
  { key: 'd', color: 'green' },
  { key: 'e', color: 'green' },
  { key: 'f', color: 'red' },
  { key: 'g', color: 'red' },
  { key: 'h', color: 'blue' },
  { key: 'i', color: 'green' },
  { key: 'j', color: 'blue' },
  { key: 'k', color: 'green' },
  { key: 'l', color: 'purple' },
  { key: 'm', color: 'blue' },
  { key: 'n', color: 'blue' },
  { key: 'o', color: 'purple' },
  { key: 'p', color: 'orange' },
  { key: 'q', color: 'orange' },
  { key: 'r', color: 'red' },
  { key: 's', color: 'purple' },
  { key: 't', color: 'red' },
  { key: 'u', color: 'blue' },
  { key: 'v', color: 'red' },
  { key: 'w', color: 'purple' },
  { key: 'x', color: 'purple' },
  { key: 'y', color: 'blue' },
  { key: 'z', color: 'orange' },
  { key: 'æ', color: 'orange' },
  { key: 'ø', color: 'orange' },
  { key: 'å', color: 'orange' },
  { key: 'å', color: 'orange' },
  { key: 'ä', color: 'orange' },
  { key: 'ö', color: 'orange' },
  // Number keys.
  { key: '1', color: 'orange' },
  { key: '2', color: 'purple' },
  { key: '3', color: 'green' },
  { key: '4', color: 'red' },
  { key: '5', color: 'red' },
  { key: '6', color: 'blue' },
  { key: '7', color: 'blue' },
  { key: '8', color: 'green' },
  { key: '9', color: 'purple' },
  { key: '0', color: 'orange' },
  // Nonalphanumerical characters.
  { key: '.', color: 'orange' },
  { key: ',', color: 'orange' },
  { key: '?', color: 'orange' },
  { key: '/', color: 'orange' },
  { key: ':', color: 'orange' },
  { key: ';', color: 'orange' },
  { key: '\'', color: 'orange' },
  { key: '\"', color: 'orange' },
  { key: '\\', color: 'orange' },
  { key: '[', color: 'orange' },
  { key: ']', color: 'orange' },
  { key: '{', color: 'orange' },
  { key: '}', color: 'orange' },
  { key: '=', color: 'orange' },
  { key: '+', color: 'orange' },
  { key: '-', color: 'orange' },
  { key: '_', color: 'orange' },
  { key: ')', color: 'orange' },
  { key: '(', color: 'purple' },
  { key: '*', color: 'orange' },
  { key: '&', color: 'orange' },
  { key: '^', color: 'orange' },
  { key: '%', color: 'orange' },
  { key: '$', color: 'orange' },
  { key: '#', color: 'green' },
  { key: '@', color: 'purple' },
  { key: '!', color: 'orange' },
];
