// Default da-DK fish game levels.
export const da = [
  {
    "id": 0,
    "name": "Level 1",
    "words": [
      'fa', 'der', 'men', 'kat', 'to', 'uge', 'sad', 'af', 'saks',
      'det', 'en', 'otte', 'sort', 'mor', 'drak', 'godt', 'hund',
      'eller', 'skulle', 'nej', 'ville', 'druer', 'vin', 'fugl', 'tre',
      'leg', 'æg', 'barn', 'smuk', 'rød', 'nat', 'kvinde', 'sort', 'pige', 'kone', 'mand', 'bror', 'far',
      'ser', 'bjørn', 'vand', 'bøf', 'ænder', 'vinen', 'selv', 'hendes', 'åben', 'grøn',
      'unge', 'held', 'egen', 'kære', 'mary', 'kød', 'navn', 'kald', 'hils',
      'ind', 'hver', 'vrede', 'lægen', 'onkle', 'davs', 'tante', 'mindst',
      'snakke', 'hen', 'sæt', 'fest', 'sid', 'ryger', 'nar', 'brød', 'fjern',
      'vaere', 'stærke', 'bo', 'hele', 'the', 'midt', 'høj', 'føle', 'højre',
      'venstre', 'hun', 'også', 'elsker', 'penge', 'altså', 'vise', 'blå',
      'stole', 'hul', 'skrev', 'plads', 'rend', 'this', 'enten', 'hjerte',
      'klog', 'års', 'uh', 'vidt', 'rar', 'land', 'næse', 'lavet', 'hånd',
      'aften', 'rolig', 'rør', 'max', 'bare', 'har', 'tide', 'bed', 'røre', 'vi',
      'lyset', 'svare', 'visse', 'bond', 'musik', 'søde', 'ham', 'hjælp', 'tog',
      'slap', 'tale', 'på', 'snak', 'hva', 'aftes', 'ej', 'fleste', 'sov', 'både',
      'mindst', 'tjene', 'bog', 'luft', 'sørg', 'følte', 'sejt', 'rock', 'kniv',
      'skifte', 'miles', 'spiste', 'folk', 'sin', 'gang', 'fandt', 'lade', 'fart',
      'stand', 'bob', 'sørg', 'mark', 'regel', 'vidst', 'mørkt', 'for', 'bruge',
      'snart', 'mange', 'lille', 'gift', 'vent', 'hel', 'nemt', 'herre', 'grin',
      'skib', 'date', 'kate', 'smide', 'ofre', 'skabe', 'tit', 'gemt', 'sir', 'klar',
      'fred', 'fin', 'stjal', 'slag', 'doc', 'what', 'halv', 'an', 'dit', 'ring',
      'helst', 'york', 'hed', 'tjek', 'cirka', 'dæk', 'høj', 'send', 'have', 'hårdt',
      'yeah', 'øjne', 'til', 'baby', 'fald', 'enig', 'hop', 'flok', 'tøs', 'sal',
      'sten', 'gør', 'saft', 'han', 'sjovt', 'nyt', 'kig', 'varm', 'salt', 'lagt', 'tabt',
      'dens', 'smut', 'guld', 'nået', 'bevis', 'rig', 'bag', 'hårdt', 'danse', 'råd', 'vare',
      'sprog', 'scene', 'ret', 'og', 'hos', 'højt', 'ære', 'lugte', 'ferie', 'sko', 'lyder',
      'seng', 'ven', 'kan', 'ikke', 'end', 'ske', 'ord', 'vinde', 'smil', 'unger', 'lyve', 'ramme',
      'pakke', 'spil', 'leder', 'slå', 'sket', 'aldrig', 'jul', 'flyt', 'føles', 'løber', 'gid',
      'kaste', 'side', 'vær', 'svin', 'kugle', 'herop', 'jo', 'før', 'åh', 'slår', 'gæt', 'høje',
      'rejste', 'vej', 'slut', 'bør', 'bar', 'låne', 'knap', 'hent', 'vores', 'kom', 'tid', 'flot',
      'står', 'rum', 'skøre', 'hank', 'syge', 'måde', 'sådan', 'ked', 'glem', 'dyr', 'fyldt', 'ryg',
      'vogn', 'os', 'fem', 'mest', 'næste', 'king', 'lige', 'gået', 'rundt', 'ovre', 'klap', 'radio',
      'lå', 'travlt', 'prøv', 'svært', 'få', 'spørg', 'boss', 'sødt', 'ekstra', 'nåede',
      'time', 'kage', 'te', 'kaffe', 'deres', 'hvor', 'morgen', 'ost', 'hjem',
      'kok', 'siger', 'mit', 'bank', 'tak', 'du', 'goddag', 'ja', 'hest',
      'chef', 'april', 'juni', 'fra', 'august', 'politi', 'juli', 'marts',
      'fredag', 'skål', 'hvad', 'skriver', 'hvilken', 'fisk', 'hvilke', 'kjole', 'mens',
      'går', 'kone', 'leger', 'and', 'efter', 'farvel', 'maj', 'godt', 'skole', 'are',
      'evigt', 'over', 'tage', 'dør', 'træt', 'ild', 'liste', 'ud', 'blod', 'sa', 'øl',
      'målet', 'blot', 'tro', 'måske', 'kun', 'lyst', 'passe', 'samle', 'igen', 'sine', 'føre',
      'fine', 'må', 'ved', 'tøj', 'plan', 'mund', 'tunge', 'tror', 'styr', 'norge', 'især', 'flyet',
      'data', 'meget', 'koster', 'lam', 'fod', 'arm', 'krop', 'ansat', 'læge', 'ti', 'glad',
      'fa', 'der', 'men', 'kat', 'to', 'uge', 'sad', 'af', 'saks',
      'det', 'en', 'otte', 'sort', 'mor', 'drak', 'godt', 'hund',
      'eller', 'skulle', 'nej', 'ville', 'druer', 'vin', 'fugl', 'tre',
      'leg', 'æg', 'barn', 'smuk', 'rød', 'nat', 'kvinde', 'sort', 'pige', 'kone', 'mand', 'bror', 'far',
      'ser', 'bjørn', 'vand', 'bøf', 'ænder', 'vinen', 'selv', 'hendes', 'åben', 'grøn',
      'unge', 'held', 'egen', 'kære', 'mary', 'kød', 'navn', 'kald', 'hils',
      'ind', 'hver', 'vrede', 'lægen', 'onkle', 'davs', 'tante', 'mindst',
      'snakke', 'hen', 'sæt', 'fest', 'sid', 'ryger', 'nar', 'brød', 'fjern',
    ]
  },
  {
    "id": 1,
    "name": "Level 2",
    "words": [
      'bygge', 'muligvis', 'besøg', 'arbejdet', 'spurgte', 'mester', 'himlen', 'amerikanske', 'hjælpe',
      'stykker', 'spiller', 'partner', 'desuden', 'prinsesse', 'herovre', 'låst', 'dronning', 'historier',
      'spørgsmål', 'fordi', 'plejede', 'trækker', 'enkelt', 'forældre', 'kræver', 'handler', 'fornøjelse',
      'fremtiden', 'overstået', 'stakkels', 'seriøst', 'overfor', 'ændret', 'ramme', 'fuldstændig', 'utroligt',
      'havde', 'præsident', 'syntes', 'billeder', 'skuespiller', 'drikker', 'nervøs', 'deroppe', 'mærkeligt',
      'bevæger', 'systemet', 'såret', 'gutter', 'mellem', 'dårlig', 'forretning', 'flygte', 'glæde', 'enhver',
      'virkeligheden', 'selvfølgelig', 'kærlighed', 'henter', 'tjener', 'brænder', 'sergent', 'korrekt', 'thomas',
      'gemmer', 'hjertet', 'telefonen', 'opmærksomhed', 'forskel', 'gruppe', 'tilgiv', 'skæbne', 'noget', 'hånd',
      'kammerat', 'lærte', 'kæmper', 'hemmelighed', 'halvdelen', 'washington', 'træd', 'dommer', 'spændende',
      'bussen', 'vidunderligt', 'regeringen', 'ødelagde', 'bringer', 'nærheden', 'morgenmad', 'besøge', 'måned',
      'forkert', 'hvornår', 'kilometer', 'farlig', 'kamera', 'nærmer', 'gjorde', 'betyder', 'frokost', 'professor',
      'sælger', 'område', 'heldige', 'mødtes', 'rejste', 'heller', 'betaler', 'skildpadde', 'forsvandt', 'hjælper',
      'arbejder', 'cheffen', 'direktøren', 'undskyld', 'kæmpe', 'fortsæt', 'køkkenet', 'situationen', 'båden',
      'hinanden', 'træk', 'morsomt', 'derhjemme', 'ordrer', 'tilfreds', 'græde', 'personer', 'bedstefar', 'smulle',
      'sidde', 'bedstemor', 'søskende', 'dommeren', 'pigen', 'edderkop', 'drømme', 'klasse', 'fanget', 'nemlig', 'ulykke',
      'bekymrer', 'problemet', 'forfærdeligt', 'england', 'fætter', 'vågn', 'behøver', 'øjeblik', 'mindst',
      'allesammen', 'godaften', 'ligesom', 'sindssyg', 'hvabehar', 'kontakt', 'muligt', 'sekund', 'løjtnant',
      'dengang', 'fortæller', 'værsgo', 'mennesker', 'mødes', 'oplysninger', 'fortræd', 'bukser', 'nåede',
      'vrede', 'spørger', 'familie', 'soldaten', 'vagt', 'åbenbart', 'allergisk', 'kyllingefilet', 'Centrum',
      'Glædelig', 'Diesel', 'Beklager', 'Blyfri', 'hedder', 'benzin', 'universitetet', 'Godeftermiddag',
      'Lækkert', 'problem', 'hedder', 'kalender', 'markerede', 'jubilæum', 'stopuret', 'otteoghalvtres',
      'Væguret', 'væggen', 'hænger', 'kunne', 'computer', 'bruger', 'afsted', 'ligeud', 'Parret', 'vittighed',
      'grinede', 'solnedgangen', 'Turisterne', 'Stationen', 'herfra', 'Grøntsager', 'appelsiner', 'bananer',
      'jordbaær', 'æbler', 'pærer', 'citroner', 'melon', 'vandmelon', 'tomater', 'agurker', 'gulerødder',
      'klasseværelse', 'programmør', 'hvidvin', 'grøntsager', 'oksekød', 'Hovedretten', 'Svinekød',
      'kylling', 'grøntsager', 'dessert', 'sodavand', 'øllen', 'mælk', 'gris', 'kyllingesuppe', 'Hospitalet',
      'lækkert', 'Aftenens', 'ekstremt', 'hovedret', 'voksne', 'ubehagelige', 'lillebroren', 'bløder',
      'Storebroren', 'menneskelige', 'brystsmerter', 'sygeplejerske', 'kvindelig', 'mødelokalet',
      'politibetjent', 'uniform', 'ingeniør', 'undersøger', 'instruktioner', 'Fabrikslederen', 'giver',
      'majblomster', 'Skudårsdag', 'markerer', 'efteråret', 'Aprilbyger', 'foråret', 'halvkugle', 'nordlige',
      'bringer', 'vinteren', 'sommeren', 'giftes', 'begynder', 'Halloween', 'enogtredivte', 'måneder',
      'ottende', 'yndlingstal', 'Kaffekanden', 'fuld', 'helsekost', 'whiskey',
      'forkert', 'hvornår', 'kilometer', 'farlig', 'kamera', 'nærmer', 'gjorde', 'betyder', 'frokost', 'professor',
      'sælger', 'område', 'heldige', 'mødtes', 'rejste', 'heller', 'betaler', 'skildpadde', 'forsvandt', 'hjælper',
      'arbejder', 'cheffen', 'direktøren', 'undskyld', 'kæmpe', 'fortsæt', 'køkkenet', 'situationen', 'båden',
      'hinanden', 'træk', 'morsomt', 'derhjemme', 'ordrer', 'tilfreds', 'græde', 'personer', 'bedstefar', 'smulle',
      'sidde', 'bedstemor', 'søskende', 'dommeren', 'pigen', 'edderkop', 'drømme', 'klasse', 'fanget', 'nemlig', 'ulykke',
      'bekymrer', 'problemet', 'forfærdeligt', 'england', 'fætter', 'vågn', 'behøver', 'øjeblik', 'mindst',
      'bygge', 'muligvis', 'besøg', 'arbejdet', 'spurgte', 'mester', 'himlen', 'amerikanske', 'hjælpe',
      'stykker', 'spiller', 'partner', 'desuden', 'prinsesse', 'herovre', 'låst', 'dronning', 'historier',
      'spørgsmål', 'fordi', 'plejede', 'trækker', 'enkelt', 'forældre', 'kræver', 'handler', 'fornøjelse',
      'fremtiden', 'overstået', 'stakkels', 'seriøst', 'overfor', 'ændret', 'ramme', 'fuldstændig', 'utroligt',
      'havde', 'præsident', 'syntes', 'billeder', 'skuespiller', 'drikker', 'nervøs', 'deroppe', 'mærkeligt',
      'bevæger', 'systemet', 'såret', 'gutter', 'mellem', 'dårlig', 'forretning', 'flygte', 'glæde', 'enhver',
      'virkeligheden', 'selvfølgelig', 'kærlighed', 'henter', 'tjener', 'brænder', 'sergent', 'korrekt', 'thomas',
      'gemmer', 'hjertet', 'telefonen', 'opmærksomhed', 'forskel', 'gruppe', 'tilgiv', 'skæbne', 'noget', 'hånd',
      'kammerat', 'lærte', 'kæmper', 'hemmelighed', 'halvdelen', 'washington', 'træd', 'dommer', 'spændende',
      'bussen', 'vidunderligt', 'regeringen', 'ødelagde', 'bringer', 'nærheden', 'morgenmad', 'besøge', 'måned',
      'forkert', 'hvornår', 'kilometer', 'farlig', 'kamera', 'nærmer', 'gjorde', 'betyder', 'frokost', 'professor',
      'sælger', 'område', 'heldige', 'mødtes', 'rejste', 'heller', 'betaler', 'skildpadde', 'forsvandt', 'hjælper',
      'arbejder', 'cheffen', 'direktøren', 'undskyld', 'kæmpe', 'fortsæt', 'køkkenet', 'situationen', 'båden',
      'hinanden', 'træk', 'morsomt', 'derhjemme', 'ordrer', 'tilfreds', 'græde', 'personer', 'bedstefar', 'smulle',
    ]
  },
  {
    "id": 2,
    "name": "Level 3",
    "words": [
      'helst', 'york', 'hed', 'tjek', 'cirka', 'dæk', 'høj', 'send', 'have', 'hårdt',
      'yeah', 'øjne', 'til', 'baby', 'fald', 'enig', 'hop', 'flok', 'tøs', 'sal',
      'sten', 'gør', 'saft', 'han', 'sjovt', 'nyt', 'kig', 'varm', 'salt', 'lagt', 'tabt',
      'dens', 'smut', 'guld', 'nået', 'bevis', 'rig', 'bag', 'hårdt', 'danse', 'råd', 'vare',
      'sprog', 'scene', 'ret', 'og', 'hos', 'højt', 'ære', 'lugte', 'ferie', 'sko', 'lyder',
      'seng', 'ven', 'kan', 'ikke', 'end', 'ske', 'ord', 'vinde', 'smil', 'unger', 'lyve', 'ramme',
      'pakke', 'spil', 'leder', 'slå', 'sket', 'aldrig', 'jul', 'flyt', 'føles', 'løber', 'gid',
      'kaste', 'side', 'vær', 'svin', 'kugle', 'herop', 'jo', 'før', 'åh', 'slår', 'gæt', 'høje',
      'rejste', 'vej', 'slut', 'bør', 'bar', 'låne', 'knap', 'hent', 'vores', 'kom', 'tid', 'flot',
      'står', 'rum', 'skøre', 'hank', 'syge', 'måde', 'sådan', 'ked', 'glem', 'dyr', 'fyldt', 'ryg',
      'vogn', 'os', 'fem', 'mest', 'næste', 'king', 'lige', 'gået', 'rundt', 'ovre', 'klap', 'radio',
      'lå', 'travlt', 'prøv', 'svært', 'få', 'spørg', 'boss', 'sødt', 'ekstra', 'nåede',
      'time', 'kage', 'te', 'kaffe', 'deres', 'hvor', 'morgen', 'ost', 'hjem',
      'kok', 'siger', 'mit', 'bank', 'tak', 'du', 'goddag', 'ja', 'hest',
      'chef', 'april', 'juni', 'fra', 'august', 'politi', 'juli', 'marts',
      'fredag', 'skål', 'hvad', 'skriver', 'hvilken', 'fisk', 'hvilke', 'kjole', 'mens',
      'går', 'kone', 'leger', 'and', 'efter', 'farvel', 'maj', 'godt', 'skole', 'are',
      'evigt', 'over', 'tage', 'dør', 'træt', 'ild', 'liste', 'ud', 'blod', 'sa', 'øl',
      'målet', 'blot', 'tro', 'måske', 'kun', 'lyst', 'passe', 'samle', 'igen', 'sine', 'føre',
      'fine', 'må', 'ved', 'tøj', 'plan', 'mund', 'tunge', 'tror', 'styr', 'norge', 'især', 'flyet',
      'data', 'meget', 'koster', 'lam', 'fod', 'arm', 'krop', 'ansat', 'læge', 'ti', 'glad',
      'bygge', 'muligvis', 'besøg', 'arbejdet', 'spurgte', 'mester', 'himlen', 'amerikanske', 'hjælpe',
      'stykker', 'spiller', 'partner', 'desuden', 'prinsesse', 'herovre', 'låst', 'dronning', 'historier',
      'spørgsmål', 'fordi', 'plejede', 'trækker', 'enkelt', 'forældre', 'kræver', 'handler', 'fornøjelse',
      'fremtiden', 'overstået', 'stakkels', 'seriøst', 'overfor', 'ændret', 'ramme', 'fuldstændig', 'utroligt',
      'havde', 'præsident', 'syntes', 'billeder', 'skuespiller', 'drikker', 'nervøs', 'deroppe', 'mærkeligt',
      'bevæger', 'systemet', 'såret', 'gutter', 'mellem', 'dårlig', 'forretning', 'flygte', 'glæde', 'enhver',
      'virkeligheden', 'selvfølgelig', 'kærlighed', 'henter', 'tjener', 'brænder', 'sergent', 'korrekt', 'thomas',
      'gemmer', 'hjertet', 'telefonen', 'opmærksomhed', 'forskel', 'gruppe', 'tilgiv', 'skæbne', 'noget', 'hånd',
      'kammerat', 'lærte', 'kæmper', 'hemmelighed', 'halvdelen', 'washington', 'træd', 'dommer', 'spændende',
      'bussen', 'vidunderligt', 'regeringen', 'ødelagde', 'bringer', 'nærheden', 'morgenmad', 'besøge', 'måned',
      'forkert', 'hvornår', 'kilometer', 'farlig', 'kamera', 'nærmer', 'gjorde', 'betyder', 'frokost', 'professor',
      'sælger', 'område', 'heldige', 'mødtes', 'rejste', 'heller', 'betaler', 'skildpadde', 'forsvandt', 'hjælper',
      'arbejder', 'cheffen', 'direktøren', 'undskyld', 'kæmpe', 'fortsæt', 'køkkenet', 'situationen', 'båden',
      'hinanden', 'træk', 'morsomt', 'derhjemme', 'ordrer', 'tilfreds', 'græde', 'personer', 'bedstefar', 'smulle',
      'sidde', 'bedstemor', 'søskende', 'dommeren', 'pigen', 'edderkop', 'drømme', 'klasse', 'fanget', 'nemlig', 'ulykke',
      'bekymrer', 'problemet', 'forfærdeligt', 'england', 'fætter', 'vågn', 'behøver', 'øjeblik', 'mindst',
      'allesammen', 'godaften', 'ligesom', 'sindssyg', 'hvabehar', 'kontakt', 'muligt', 'sekund', 'løjtnant',
      'dengang', 'fortæller', 'værsgo', 'mennesker', 'mødes', 'oplysninger', 'fortræd', 'bukser', 'nåede',
      'vrede', 'spørger', 'familie', 'soldaten', 'vagt', 'åbenbart', 'allergisk', 'kyllingefilet', 'Centrum',
      'Glædelig', 'Diesel', 'Beklager', 'Blyfri', 'hedder', 'benzin', 'universitetet', 'Godeftermiddag',
      'Lækkert', 'problem', 'hedder', 'kalender', 'markerede', 'jubilæum', 'stopuret', 'otteoghalvtres',
      'Væguret', 'væggen', 'hænger', 'kunne', 'computer', 'bruger', 'afsted', 'ligeud', 'Parret', 'vittighed',
      'grinede', 'solnedgangen', 'Turisterne', 'Stationen', 'herfra', 'Grøntsager', 'appelsiner', 'bananer',
      'jordbaær', 'æbler', 'pærer', 'citroner', 'melon', 'vandmelon', 'tomater', 'agurker', 'gulerødder',
      'klasseværelse', 'programmør', 'hvidvin', 'grøntsager', 'oksekød', 'Hovedretten', 'Svinekød',
      'kylling', 'grøntsager', 'dessert', 'sodavand', 'øllen', 'mælk', 'gris', 'kyllingesuppe', 'Hospitalet',
      'lækkert', 'Aftenens', 'ekstremt', 'hovedret', 'voksne', 'ubehagelige', 'lillebroren', 'bløder',
      'Storebroren', 'menneskelige', 'brystsmerter', 'sygeplejerske', 'kvindelig', 'mødelokalet',
      'politibetjent', 'uniform', 'ingeniør', 'undersøger', 'instruktioner', 'Fabrikslederen', 'giver',
      'majblomster', 'Skudårsdag', 'markerer', 'efteråret', 'Aprilbyger', 'foråret', 'halvkugle', 'nordlige',
      'bringer', 'vinteren', 'sommeren', 'giftes', 'begynder', 'Halloween', 'enogtredivte', 'måneder',
      'ottende', 'yndlingstal', 'Kaffekanden', 'fuld', 'helsekost', 'whiskey',
    ]
  },
]
