// Default nb-NO fish game levels.
export const nb = [
  {
    "id": 0,
    "name": "Level 1",
    "words": [
      'fa', 'ja', 'fdsa', 'aks', 'alf', 'sad', 'af', 'saks',
      'frfd', 'jujk', 'fded', 'drak', 'farfar', 'kdieiekd',
      'eller', 'skulle', 'ville', 'druer', 'fugl', 'hund',
      'kat', 'kage', 'kaffe', 'mor', 'far', 'bror', 'kat', 'fugl',
      'en', 'mand', 'kvinde', 'barn', 'godt', 'skole',
      'deres', 'hvor', 'ujuk', 'hvorfor', 'skal', 'hvad', 'hund', 'der', 'hvem',
      'skriver', 'hvilken', 'sort', 'hvilke', 'kjole', 'mens', 'mad', 'onsadg', 'jeg',
      'efter', 'farvel', 'otte', 'uge', 'mit', 'bank', 'tak', 'du',
      'goddag', 'ja', 'tre', 'morgen', 'and', 'hest', 'time', 'leg', 'nat', 'hjem',
      'maj', 'ost', 'te', 'sondag', 'vand', 'kok', 'chef', 'april', 'fisk', 'juni', 'to', 'fra', 'august',
      'vin', 'politi', 'juli', 'marts', 'nej', 'fredag', 'siger', 'nul',
      'frfd', 'jujk', 'fded', 'drak', 'farfar', 'kdieiekd',
      'eller', 'skulle', 'ville', 'druer', 'fugl', 'hund',
      'kat', 'kage', 'kaffe', 'mor', 'far', 'bror', 'kat', 'fugl',
      'en', 'mand', 'kvinde', 'barn', 'godt', 'skole',
      'deres', 'hvor', 'ujuk', 'hvorfor', 'skal', 'hvad', 'hund', 'der', 'hvem',
      'skriver', 'hvilken', 'sort', 'hvilke', 'kjole', 'mens', 'mad', 'onsadg', 'jeg',
      'efter', 'farvel', 'otte', 'uge', 'mit', 'bank', 'tak', 'du',
      'goddag', 'ja', 'tre', 'morgen', 'and', 'hest', 'time', 'leg', 'nat', 'hjem',
      'maj', 'ost', 'te', 'sondag', 'vand', 'kok', 'chef', 'april', 'fisk', 'juni', 'to', 'fra', 'august',
      'vin', 'politi', 'juli', 'marts', 'nej', 'fredag', 'siger', 'nul',
      'frfd', 'jujk', 'fded', 'drak', 'farfar', 'kdieiekd',
      'eller', 'skulle', 'ville', 'druer', 'fugl', 'hund',
      'kat', 'kage', 'kaffe', 'mor', 'far', 'bror', 'kat', 'fugl',
      'en', 'mand', 'kvinde', 'barn', 'godt', 'skole',
      'deres', 'hvor', 'ujuk', 'hvorfor', 'skal', 'hvad', 'hund', 'der', 'hvem',
      'skriver', 'hvilken', 'sort', 'hvilke', 'kjole', 'mens', 'mad', 'onsadg', 'jeg',
      'efter', 'farvel', 'otte', 'uge', 'mit', 'bank', 'tak', 'du',
      'goddag', 'ja', 'tre', 'morgen', 'and', 'hest', 'time', 'leg', 'nat', 'hjem',
      'maj', 'ost', 'te', 'sondag', 'vand', 'kok', 'chef', 'april', 'fisk', 'juni', 'to', 'fra', 'august',
      'vin', 'politi', 'juli', 'marts', 'nej', 'fredag', 'siger', 'nul',
      'goddag', 'ja', 'tre', 'morgen', 'and', 'hest', 'time', 'leg', 'nat', 'hjem',
      'maj', 'ost', 'te', 'sondag', 'vand', 'kok', 'chef', 'april', 'fisk', 'juni', 'to', 'fra', 'august',
      'vin', 'politi', 'juli', 'marts', 'nej', 'fredag', 'siger', 'nul',
      'frfd', 'jujk', 'fded', 'drak', 'farfar', 'kdieiekd',
      'eller', 'skulle', 'ville', 'druer', 'fugl', 'hund',
      'kat', 'kage', 'kaffe', 'mor', 'far', 'bror', 'kat', 'fugl',
      'en', 'mand', 'kvinde', 'barn', 'godt', 'skole',
      'deres', 'hvor', 'ujuk', 'hvorfor', 'skal', 'hvad', 'hund', 'der', 'hvem',
      'skriver', 'hvilken', 'sort', 'hvilke', 'kjole', 'mens', 'mad', 'onsadg', 'jeg',
      'efter', 'farvel', 'otte', 'uge', 'mit', 'bank', 'tak', 'du',
      'goddag', 'ja', 'tre', 'morgen', 'and', 'hest', 'time', 'leg', 'nat', 'hjem',
      'maj', 'ost', 'te', 'sondag', 'vand', 'kok', 'chef', 'april', 'fisk', 'juni', 'to', 'fra', 'august',
      'vin', 'politi', 'juli', 'marts', 'nej', 'fredag', 'siger', 'nul',
      'frfd', 'jujk', 'fded', 'drak', 'farfar', 'kdieiekd',
      'eller', 'skulle', 'ville', 'druer', 'fugl', 'hund',
      'kat', 'kage', 'kaffe', 'mor', 'far', 'bror', 'kat', 'fugl',
      'en', 'mand', 'kvinde', 'barn', 'godt', 'skole',
      'deres', 'hvor', 'ujuk', 'hvorfor', 'skal', 'hvad', 'hund', 'der', 'hvem',
      'skriver', 'hvilken', 'sort', 'hvilke', 'kjole', 'mens', 'mad', 'onsadg', 'jeg',
      'efter', 'farvel', 'otte', 'uge', 'mit', 'bank', 'tak', 'du',
      'goddag', 'ja', 'tre', 'morgen', 'and', 'hest', 'time', 'leg', 'nat', 'hjem',
      'maj', 'ost', 'te', 'sondag', 'vand', 'kok', 'chef', 'april', 'fisk', 'juni', 'to', 'fra', 'august',
      'vin', 'politi', 'juli', 'marts', 'nej', 'fredag', 'siger', 'nul',
    ]
  },
];
